-- Product name/description translations for 16 languages (Postgres; mirrors data.sql).
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','de','Rolex Submariner Date','Ikonische 41-mm-Taucheruhr aus Oystersteel mit Cerachrom-Lünette.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','de','Omega Speedmaster Moonwatch','Legendärer Handaufzug-Chronograph — die erste Uhr auf dem Mond.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','de','MacBook Pro 16" M3 Max','36 GB Speicher, 1 TB SSD und Liquid Retina XDR Display.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','de','Dell XPS 15 OLED','15,6-Zoll-3,5K-OLED, Core i9, 32 GB RAM und RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','de','iPhone 15 Pro Max','Titan in Luftfahrtqualität, A17 Pro Chip, 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','de','Samsung Galaxy S24 Ultra','200-MP-Kamera, S Pen und 6,8-Zoll-AMOLED-Display.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','de','Sony WH-1000XM5','Kabellose Over-Ear-Kopfhörer mit Geräuschunterdrückung.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','de','Apple AirPods Pro 2','Aktive Geräuschunterdrückung, USB-C und adaptives Audio.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','de','Bose SoundLink Flex','Robuster, wasserdichter Bluetooth-Lautsprecher mit tiefem Bass.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','de','Louis Vuitton Keepall 55','Reisetasche aus Monogram-Canvas — Symbol luxuriösen Reisens.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','de','Montblanc Meisterstück 149','Vergoldeter Füllfederhalter aus edlem schwarzem Harz.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','de','Ray-Ban Aviator Classic','Zeitlose Sonnenbrille mit Goldrahmen und G-15-Gläsern.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','fr','Rolex Submariner Date','Montre de plongée 41 mm en Oystersteel avec lunette Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','fr','Omega Speedmaster Moonwatch','Chronographe légendaire à remontage manuel — première montre sur la Lune.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','fr','MacBook Pro 16" M3 Max','36 Go de mémoire, SSD 1 To et écran Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','fr','Dell XPS 15 OLED','OLED 3,5K de 15,6 pouces, Core i9, 32 Go de RAM et RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','fr','iPhone 15 Pro Max','Titane de qualité aérospatiale, puce A17 Pro, 512 Go.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','fr','Samsung Galaxy S24 Ultra','Appareil photo 200 Mpx, S Pen et écran AMOLED de 6,8 pouces.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','fr','Sony WH-1000XM5','Casque sans fil à réduction de bruit de premier plan.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','fr','Apple AirPods Pro 2','Réduction de bruit active, charge USB-C et audio adaptatif.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','fr','Bose SoundLink Flex','Enceinte Bluetooth portable étanche aux basses profondes.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','fr','Louis Vuitton Keepall 55','Sac de voyage en toile Monogram, symbole du voyage de luxe.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','fr','Montblanc Meisterstück 149','Stylo plume plaqué or, façonné en précieuse résine noire.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','fr','Ray-Ban Aviator Classic','Lunettes de soleil intemporelles à monture dorée et verres G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','es','Rolex Submariner Date','Reloj de buceo de 41 mm en Oystersteel con bisel Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','es','Omega Speedmaster Moonwatch','Cronógrafo legendario de cuerda manual — el primer reloj en la Luna.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','es','MacBook Pro 16" M3 Max','36 GB de memoria, SSD de 1 TB y pantalla Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','es','Dell XPS 15 OLED','OLED 3,5K de 15,6 pulgadas, Core i9, 32 GB de RAM y RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','es','iPhone 15 Pro Max','Titanio de grado aeroespacial, chip A17 Pro y 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','es','Samsung Galaxy S24 Ultra','Cámara de 200 MP, S Pen y pantalla AMOLED de 6,8 pulgadas.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','es','Sony WH-1000XM5','Auriculares inalámbricos con cancelación de ruido líder.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','es','Apple AirPods Pro 2','Cancelación activa de ruido, carga USB-C y audio adaptativo.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','es','Bose SoundLink Flex','Altavoz Bluetooth portátil resistente al agua con graves profundos.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','es','Louis Vuitton Keepall 55','Bolsa de viaje en lona Monogram, símbolo del viaje de lujo.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','es','Montblanc Meisterstück 149','Pluma estilográfica chapada en oro, en preciada resina negra.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','es','Ray-Ban Aviator Classic','Gafas de sol atemporales con montura dorada y lentes G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','it','Rolex Submariner Date','Orologio subacqueo 41 mm in Oystersteel con lunetta Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','it','Omega Speedmaster Moonwatch','Cronografo leggendario a carica manuale — il primo orologio sulla Luna.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','it','MacBook Pro 16" M3 Max','36 GB di memoria, SSD da 1 TB e display Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','it','Dell XPS 15 OLED','OLED 3,5K da 15,6 pollici, Core i9, 32 GB di RAM e RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','it','iPhone 15 Pro Max','Titanio di grado aerospaziale, chip A17 Pro e 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','it','Samsung Galaxy S24 Ultra','Fotocamera da 200 MP, S Pen e display AMOLED da 6,8 pollici.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','it','Sony WH-1000XM5','Cuffie over-ear wireless con cancellazione del rumore.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','it','Apple AirPods Pro 2','Cancellazione attiva del rumore, ricarica USB-C e audio adattivo.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','it','Bose SoundLink Flex','Altoparlante Bluetooth portatile impermeabile con bassi profondi.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','it','Louis Vuitton Keepall 55','Borsa da viaggio in tela Monogram, simbolo del viaggio di lusso.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','it','Montblanc Meisterstück 149','Penna stilografica placcata oro in pregiata resina nera.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','it','Ray-Ban Aviator Classic','Occhiali da sole senza tempo con montatura dorata e lenti G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','pt','Rolex Submariner Date','Relógio de mergulho de 41 mm em Oystersteel com luneta Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','pt','Omega Speedmaster Moonwatch','Cronógrafo lendário de corda manual — o primeiro relógio na Lua.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','pt','MacBook Pro 16" M3 Max','36 GB de memória, SSD de 1 TB e tela Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','pt','Dell XPS 15 OLED','OLED 3,5K de 15,6 polegadas, Core i9, 32 GB de RAM e RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','pt','iPhone 15 Pro Max','Titânio de nível aeroespacial, chip A17 Pro e 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','pt','Samsung Galaxy S24 Ultra','Câmera de 200 MP, S Pen e tela AMOLED de 6,8 polegadas.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','pt','Sony WH-1000XM5','Fones de ouvido sem fio com cancelamento de ruído.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','pt','Apple AirPods Pro 2','Cancelamento ativo de ruído, carga USB-C e áudio adaptável.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','pt','Bose SoundLink Flex','Caixa de som Bluetooth portátil à prova d''água com graves profundos.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','pt','Louis Vuitton Keepall 55','Mala de viagem em lona Monogram, símbolo da viagem de luxo.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','pt','Montblanc Meisterstück 149','Caneta-tinteiro banhada a ouro em preciosa resina preta.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','pt','Ray-Ban Aviator Classic','Óculos de sol atemporais com armação dourada e lentes G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','tr','Rolex Submariner Date','Cerachrom çerçeveli 41 mm Oystersteel dalış saati.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','tr','Omega Speedmaster Moonwatch','Efsanevi kurmalı kronograf — Ay''da giyilen ilk saat.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','tr','MacBook Pro 16" M3 Max','36 GB bellek, 1 TB SSD ve Liquid Retina XDR ekran.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','tr','Dell XPS 15 OLED','15,6 inç 3,5K OLED, Core i9, 32 GB RAM ve RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','tr','iPhone 15 Pro Max','Havacılık sınıfı titanyum, A17 Pro çip ve 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','tr','Samsung Galaxy S24 Ultra','200 MP kamera, S Pen ve 6,8 inç AMOLED ekran.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','tr','Sony WH-1000XM5','Sektör lideri kablosuz kulak üstü gürültü önleyici kulaklık.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','tr','Apple AirPods Pro 2','Aktif gürültü önleme, USB-C şarj ve uyarlanabilir ses.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','tr','Bose SoundLink Flex','Sağlam, su geçirmez taşınabilir Bluetooth hoparlör.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','tr','Louis Vuitton Keepall 55','Monogram kanvas seyahat çantası — lüks seyahatin simgesi.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','tr','Montblanc Meisterstück 149','Değerli siyah reçineden altın kaplama dolma kalem.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','tr','Ray-Ban Aviator Classic','Altın çerçeveli, G-15 camlı zamansız güneş gözlüğü.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','az','Rolex Submariner Date','Cerachrom çərçivəli 41 mm Oystersteel dalğıc saatı.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','az','Omega Speedmaster Moonwatch','Əfsanəvi mexaniki xronoqraf — Ayda taxılan ilk saat.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','az','MacBook Pro 16" M3 Max','36 GB yaddaş, 1 TB SSD və Liquid Retina XDR ekran.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','az','Dell XPS 15 OLED','15,6 düymlük 3,5K OLED, Core i9, 32 GB RAM və RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','az','iPhone 15 Pro Max','Aerokosmik səviyyəli titan, A17 Pro çip və 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','az','Samsung Galaxy S24 Ultra','200 MP kamera, S Pen və 6,8 düymlük AMOLED ekran.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','az','Sony WH-1000XM5','Sənaye lideri simsiz qulaqlıq, səs-küyü azaldan.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','az','Apple AirPods Pro 2','Aktiv səs-küy azaltma, USB-C şarj və adaptiv audio.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','az','Bose SoundLink Flex','Möhkəm, sudan qorunan portativ Bluetooth dinamik.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','az','Louis Vuitton Keepall 55','Monogram kətan səyahət çantası — dəbdəbəli səyahət simvolu.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','az','Montblanc Meisterstück 149','Qiymətli qara qatrandan qızıl örtüklü qələm.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','az','Ray-Ban Aviator Classic','Qızıl çərçivəli, G-15 linzalı zamansız günəş eynəyi.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','ru','Rolex Submariner Date','Дайверские часы 41 мм из Oystersteel с безелем Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','ru','Omega Speedmaster Moonwatch','Легендарный механический хронограф — первые часы на Луне.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','ru','MacBook Pro 16" M3 Max','36 ГБ памяти, SSD 1 ТБ и дисплей Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','ru','Dell XPS 15 OLED','15,6-дюймовый 3,5K OLED, Core i9, 32 ГБ ОЗУ и RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','ru','iPhone 15 Pro Max','Титан авиационного класса, чип A17 Pro и 512 ГБ.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','ru','Samsung Galaxy S24 Ultra','Камера 200 Мп, S Pen и 6,8-дюймовый AMOLED-дисплей.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','ru','Sony WH-1000XM5','Беспроводные наушники с шумоподавлением высшего класса.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','ru','Apple AirPods Pro 2','Активное шумоподавление, зарядка USB-C и адаптивный звук.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','ru','Bose SoundLink Flex','Прочная водонепроницаемая портативная Bluetooth-колонка.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','ru','Louis Vuitton Keepall 55','Дорожная сумка из холста Monogram — символ роскошных путешествий.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','ru','Montblanc Meisterstück 149','Позолоченная перьевая ручка из ценной чёрной смолы.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','ru','Ray-Ban Aviator Classic','Вневременные очки в золотой оправе с линзами G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','uk','Rolex Submariner Date','Дайверський годинник 41 мм з Oystersteel із безелем Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','uk','Omega Speedmaster Moonwatch','Легендарний механічний хронограф — перший годинник на Місяці.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','uk','MacBook Pro 16" M3 Max','36 ГБ памʼяті, SSD 1 ТБ і дисплей Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','uk','Dell XPS 15 OLED','15,6-дюймовий 3,5K OLED, Core i9, 32 ГБ ОЗП і RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','uk','iPhone 15 Pro Max','Титан авіаційного класу, чип A17 Pro і 512 ГБ.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','uk','Samsung Galaxy S24 Ultra','Камера 200 Мп, S Pen і 6,8-дюймовий AMOLED-дисплей.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','uk','Sony WH-1000XM5','Бездротові навушники з шумозаглушенням найвищого класу.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','uk','Apple AirPods Pro 2','Активне шумозаглушення, заряджання USB-C та адаптивний звук.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','uk','Bose SoundLink Flex','Міцна водонепроникна портативна Bluetooth-колонка.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','uk','Louis Vuitton Keepall 55','Дорожня сумка з полотна Monogram — символ розкішних подорожей.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','uk','Montblanc Meisterstück 149','Позолочена перова ручка з цінної чорної смоли.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','uk','Ray-Ban Aviator Classic','Позачасові окуляри в золотій оправі з лінзами G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','pl','Rolex Submariner Date','Zegarek nurkowy 41 mm z Oystersteel z bezelem Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','pl','Omega Speedmaster Moonwatch','Legendarny chronograf mechaniczny — pierwszy zegarek na Księżycu.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','pl','MacBook Pro 16" M3 Max','36 GB pamięci, SSD 1 TB i ekran Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','pl','Dell XPS 15 OLED','15,6-calowy 3,5K OLED, Core i9, 32 GB RAM i RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','pl','iPhone 15 Pro Max','Tytan klasy lotniczej, chip A17 Pro i 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','pl','Samsung Galaxy S24 Ultra','Aparat 200 MP, S Pen i 6,8-calowy ekran AMOLED.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','pl','Sony WH-1000XM5','Bezprzewodowe słuchawki nauszne z redukcją szumów.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','pl','Apple AirPods Pro 2','Aktywna redukcja szumów, ładowanie USB-C i adaptacyjny dźwięk.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','pl','Bose SoundLink Flex','Wytrzymały, wodoodporny przenośny głośnik Bluetooth.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','pl','Louis Vuitton Keepall 55','Torba podróżna z płótna Monogram — symbol luksusowych podróży.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','pl','Montblanc Meisterstück 149','Pozłacane pióro wieczne z cennej czarnej żywicy.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','pl','Ray-Ban Aviator Classic','Ponadczasowe okulary w złotej oprawie z soczewkami G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','nl','Rolex Submariner Date','41 mm Oystersteel duikhorloge met Cerachrom-bezel.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','nl','Omega Speedmaster Moonwatch','Legendarische handopwind-chronograaf — het eerste horloge op de maan.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','nl','MacBook Pro 16" M3 Max','36 GB geheugen, 1 TB SSD en Liquid Retina XDR-scherm.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','nl','Dell XPS 15 OLED','15,6-inch 3,5K OLED, Core i9, 32 GB RAM en RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','nl','iPhone 15 Pro Max','Titanium van luchtvaartkwaliteit, A17 Pro-chip en 512 GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','nl','Samsung Galaxy S24 Ultra','200 MP-camera, S Pen en 6,8-inch AMOLED-scherm.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','nl','Sony WH-1000XM5','Toonaangevende draadloze over-ear koptelefoon met ruisonderdrukking.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','nl','Apple AirPods Pro 2','Actieve ruisonderdrukking, USB-C-opladen en adaptieve audio.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','nl','Bose SoundLink Flex','Robuuste, waterdichte draagbare Bluetooth-speaker met diepe bas.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','nl','Louis Vuitton Keepall 55','Reistas van Monogram-canvas — symbool van luxe reizen.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','nl','Montblanc Meisterstück 149','Verguld vulpen van kostbaar zwart hars.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','nl','Ray-Ban Aviator Classic','Tijdloze zonnebril met gouden montuur en G-15-glazen.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','ar','Rolex Submariner Date','ساعة غوص 41 مم من Oystersteel بإطار Cerachrom.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','ar','Omega Speedmaster Moonwatch','كرونوغراف يدوي أسطوري — أول ساعة على القمر.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','ar','MacBook Pro 16" M3 Max','ذاكرة 36 جيجابايت وSSD 1 تيرابايت وشاشة Liquid Retina XDR.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','ar','Dell XPS 15 OLED','شاشة OLED 3.5K مقاس 15.6 بوصة، Core i9، و32 جيجابايت وRTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','ar','iPhone 15 Pro Max','تيتانيوم بمستوى الطيران، شريحة A17 Pro و512 جيجابايت.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','ar','Samsung Galaxy S24 Ultra','كاميرا 200 ميجابكسل وS Pen وشاشة AMOLED مقاس 6.8 بوصة.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','ar','Sony WH-1000XM5','سماعات رأس لاسلكية رائدة بخاصية إلغاء الضوضاء.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','ar','Apple AirPods Pro 2','إلغاء نشط للضوضاء وشحن USB-C وصوت تكيّفي.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','ar','Bose SoundLink Flex','مكبر صوت بلوتوث محمول متين ومقاوم للماء.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','ar','Louis Vuitton Keepall 55','حقيبة سفر من قماش Monogram — رمز للسفر الفاخر.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','ar','Montblanc Meisterstück 149','قلم حبر مطلي بالذهب من الراتنج الأسود الثمين.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','ar','Ray-Ban Aviator Classic','نظارة شمسية خالدة بإطار ذهبي وعدسات G-15.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','zh','Rolex Submariner Date','41 毫米 Oystersteel 潜水表，配 Cerachrom 表圈。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','zh','Omega Speedmaster Moonwatch','传奇手动上链计时码表——首款登月腕表。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','zh','MacBook Pro 16" M3 Max','36GB 内存、1TB 固态硬盘和 Liquid Retina XDR 显示屏。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','zh','Dell XPS 15 OLED','15.6 英寸 3.5K OLED、Core i9、32GB 内存和 RTX 4070。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','zh','iPhone 15 Pro Max','航空级钛金属、A17 Pro 芯片和 512GB。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','zh','Samsung Galaxy S24 Ultra','2 亿像素摄像头、S Pen 和 6.8 英寸 AMOLED 屏幕。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','zh','Sony WH-1000XM5','业界领先的无线降噪头戴式耳机。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','zh','Apple AirPods Pro 2','主动降噪、USB-C 充电和自适应音频。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','zh','Bose SoundLink Flex','坚固防水的便携式蓝牙音箱，低音深沉。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','zh','Louis Vuitton Keepall 55','Monogram 帆布旅行袋，奢华旅行的永恒象征。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','zh','Montblanc Meisterstück 149','镀金钢笔，采用珍贵黑色树脂手工制作。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','zh','Ray-Ban Aviator Classic','永恒的金框太阳镜，配 G-15 镜片。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','ja','Rolex Submariner Date','Cerachrom ベゼルを備えた 41mm Oystersteel ダイバーズウォッチ。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','ja','Omega Speedmaster Moonwatch','伝説的な手巻きクロノグラフ — 月に着いた最初の時計。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','ja','MacBook Pro 16" M3 Max','36GB メモリ、1TB SSD、Liquid Retina XDR ディスプレイ。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','ja','Dell XPS 15 OLED','15.6 インチ 3.5K OLED、Core i9、32GB RAM、RTX 4070。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','ja','iPhone 15 Pro Max','航空宇宙グレードのチタン、A17 Pro チップ、512GB。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','ja','Samsung Galaxy S24 Ultra','2 億画素カメラ、S Pen、6.8 インチ AMOLED ディスプレイ。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','ja','Sony WH-1000XM5','業界をリードするワイヤレスノイズキャンセリングヘッドホン。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','ja','Apple AirPods Pro 2','アクティブノイズキャンセリング、USB-C 充電、適応型オーディオ。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','ja','Bose SoundLink Flex','頑丈で防水のポータブル Bluetooth スピーカー。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','ja','Louis Vuitton Keepall 55','Monogram キャンバスの旅行バッグ — ラグジュアリーな旅の象徴。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','ja','Montblanc Meisterstück 149','貴重な黒い樹脂から作られた金メッキの万年筆。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','ja','Ray-Ban Aviator Classic','G-15 レンズを備えた時代を超えたゴールドフレームのサングラス。');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','ko','Rolex Submariner Date','Cerachrom 베젤이 있는 41mm Oystersteel 다이빙 시계.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','ko','Omega Speedmaster Moonwatch','전설적인 수동 크로노그래프 — 달에 착용한 최초의 시계.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','ko','MacBook Pro 16" M3 Max','36GB 메모리, 1TB SSD, Liquid Retina XDR 디스플레이.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','ko','Dell XPS 15 OLED','15.6인치 3.5K OLED, Core i9, 32GB RAM, RTX 4070.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','ko','iPhone 15 Pro Max','항공우주급 티타늄, A17 Pro 칩, 512GB.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','ko','Samsung Galaxy S24 Ultra','2억 화소 카메라, S Pen, 6.8인치 AMOLED 디스플레이.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','ko','Sony WH-1000XM5','업계 최고의 무선 노이즈 캔슬링 헤드폰.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','ko','Apple AirPods Pro 2','액티브 노이즈 캔슬링, USB-C 충전, 적응형 오디오.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','ko','Bose SoundLink Flex','견고하고 방수되는 휴대용 블루투스 스피커.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','ko','Louis Vuitton Keepall 55','Monogram 캔버스 여행 가방 — 럭셔리 여행의 상징.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','ko','Montblanc Meisterstück 149','귀한 검은 수지로 만든 금도금 만년필.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','ko','Ray-Ban Aviator Classic','G-15 렌즈를 갖춘 시대를 초월한 골드 프레임 선글라스.');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('1','hi','Rolex Submariner Date','Cerachrom बेज़ल वाली 41mm Oystersteel डाइविंग घड़ी।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('2','hi','Omega Speedmaster Moonwatch','पौराणिक मैनुअल क्रोनोग्राफ — चंद्रमा पर पहनी गई पहली घड़ी।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('3','hi','MacBook Pro 16" M3 Max','36GB मेमोरी, 1TB SSD और Liquid Retina XDR डिस्प्ले।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('4','hi','Dell XPS 15 OLED','15.6 इंच 3.5K OLED, Core i9, 32GB RAM और RTX 4070।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('5','hi','iPhone 15 Pro Max','एयरोस्पेस-ग्रेड टाइटेनियम, A17 Pro चिप और 512GB।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('6','hi','Samsung Galaxy S24 Ultra','200MP कैमरा, S Pen और 6.8 इंच AMOLED डिस्प्ले।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('7','hi','Sony WH-1000XM5','उद्योग-अग्रणी वायरलेस नॉइज़-कैंसलिंग हेडफ़ोन।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('8','hi','Apple AirPods Pro 2','सक्रिय नॉइज़ कैंसलेशन, USB-C चार्जिंग और अनुकूली ऑडियो।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('9','hi','Bose SoundLink Flex','मजबूत, वाटरप्रूफ पोर्टेबल ब्लूटूथ स्पीकर।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('10','hi','Louis Vuitton Keepall 55','Monogram कैनवास ट्रैवल बैग — विलासिता यात्रा का प्रतीक।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('11','hi','Montblanc Meisterstück 149','कीमती काले रेज़िन से बना सोने की परत वाला फाउंटेन पेन।');
INSERT INTO product_translation (product_id, language_code, name, description) VALUES ('12','hi','Ray-Ban Aviator Classic','G-15 लेंस के साथ सुनहरे फ्रेम वाला कालातीत धूप का चश्मा।');
