-- Guest product reviews: a rating (1-5) and optional comment, no account needed.
CREATE TABLE product_review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  VARCHAR(255) NOT NULL,
    author_name VARCHAR(120) NOT NULL,
    rating      INTEGER      NOT NULL,
    comment     VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_product_review_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX idx_product_review_product ON product_review (product_id);

-- A few seed reviews so the storefront shows ratings out of the box.
INSERT INTO product_review (product_id, author_name, rating, comment, created_at) VALUES
    ('1', 'Giorgi',  5, 'Absolutely stunning timepiece — worth every tetri.',        TIMESTAMP '2026-06-15 10:20:00'),
    ('1', 'Anna',    4, 'Beautiful watch, though the bracelet took some adjusting.',  TIMESTAMP '2026-06-20 14:05:00'),
    ('3', 'Luka',    5, 'Blazing fast for video editing and the display is gorgeous.', TIMESTAMP '2026-06-22 09:00:00'),
    ('5', 'Mariam',  4, 'Great phone, the battery easily lasts all day.',             TIMESTAMP '2026-06-25 18:30:00'),
    ('8', 'Nino',    5, 'The best noise-cancelling earbuds I have ever owned.',       TIMESTAMP '2026-06-28 12:15:00'),
    ('8', 'Davit',   4, 'Excellent sound, the fit could be a little snugger.',        TIMESTAMP '2026-07-01 08:45:00');
