-- Percentage-off discount codes applied at checkout.
CREATE TABLE coupon (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(40) NOT NULL UNIQUE,
    percent_off INTEGER     NOT NULL,
    active      BOOLEAN     NOT NULL
);

INSERT INTO coupon (code, percent_off, active) VALUES
    ('WELCOME10', 10, true),
    ('LUX20',     20, true),
    ('EXPIRED',   15, false);
