-- Extra gallery images per product, shown on the product detail page.
CREATE TABLE product_image (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(255)  NOT NULL,
    url        VARCHAR(1000) NOT NULL,
    position   INTEGER       NOT NULL,
    CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

CREATE INDEX idx_product_image_product ON product_image (product_id);

INSERT INTO product_image (product_id, url, position) VALUES
    ('1','https://picsum.photos/seed/lux-1-a/800/600',1),
    ('1','https://picsum.photos/seed/lux-1-b/800/600',2),
    ('2','https://picsum.photos/seed/lux-2-a/800/600',1),
    ('2','https://picsum.photos/seed/lux-2-b/800/600',2),
    ('3','https://picsum.photos/seed/lux-3-a/800/600',1),
    ('3','https://picsum.photos/seed/lux-3-b/800/600',2),
    ('4','https://picsum.photos/seed/lux-4-a/800/600',1),
    ('4','https://picsum.photos/seed/lux-4-b/800/600',2),
    ('5','https://picsum.photos/seed/lux-5-a/800/600',1),
    ('5','https://picsum.photos/seed/lux-5-b/800/600',2),
    ('6','https://picsum.photos/seed/lux-6-a/800/600',1),
    ('6','https://picsum.photos/seed/lux-6-b/800/600',2),
    ('7','https://picsum.photos/seed/lux-7-a/800/600',1),
    ('7','https://picsum.photos/seed/lux-7-b/800/600',2),
    ('8','https://picsum.photos/seed/lux-8-a/800/600',1),
    ('8','https://picsum.photos/seed/lux-8-b/800/600',2),
    ('9','https://picsum.photos/seed/lux-9-a/800/600',1),
    ('9','https://picsum.photos/seed/lux-9-b/800/600',2),
    ('10','https://picsum.photos/seed/lux-10-a/800/600',1),
    ('10','https://picsum.photos/seed/lux-10-b/800/600',2),
    ('11','https://picsum.photos/seed/lux-11-a/800/600',1),
    ('11','https://picsum.photos/seed/lux-11-b/800/600',2),
    ('12','https://picsum.photos/seed/lux-12-a/800/600',1),
    ('12','https://picsum.photos/seed/lux-12-b/800/600',2);
