-- i18n: per-language product/category names & descriptions in relational tables
-- (portable across H2 and Postgres, unlike a Postgres-only JSONB column).
CREATE TABLE product_translation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    VARCHAR(255) NOT NULL,
    language_code VARCHAR(8)   NOT NULL,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(2000),
    CONSTRAINT fk_product_translation_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT uk_product_translation_lang UNIQUE (product_id, language_code)
);

CREATE TABLE category_translation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id   VARCHAR(255) NOT NULL,
    language_code VARCHAR(8)   NOT NULL,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(2000),
    CONSTRAINT fk_category_translation_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE,
    CONSTRAINT uk_category_translation_lang UNIQUE (category_id, language_code)
);
